//
// Created by X-ray on 3/8/2022.
//

#pragma once

#ifndef GTA_BASE_ENUMS_RAGE_HPP
#define GTA_BASE_ENUMS_RAGE_HPP
#include <player/CPlayerInfo.hpp>

namespace rage {
// blip enums start
enum class BlipIcons {
  Null,
  Circle,
  Empty,
  Cop,
  CopSearchZone,
  Square,
  PlayerArrow,
  North,
  Waypoint,
  BigCircle,
  BigCircleOutline,
  ArrowUpOutlined,
  ArrowDownOutlined,
  ArrowUp,
  ArrowDown,
  PoliceHelicopter,
  Jet,
  Number1,
  Number2,
  Number3,
  Number4,
  Number5,
  Number6,
  Number7,
  Number8,
  Number9,
  Number10,
  GTAOCrew,
  GTAOFriend,
  CableCar = 36,
  RaceFinish = 38,
  Safehouse = 40,
  Cop2,
  CopCar,
  Helicopter,
  ChatBubble = 47,
  Garage = 50,
  Drugs,
  ConvenienceStore,
  PoliceCar = 56,
  Circle2,
  CircleWithStar,
  ConvenienceStore2,
  ShieldWithStar,
  Asterisk,
  Helicopter2 = 64,
  StrangersAndFreaks = 66,
  ArmoredTruck,
  TowTruck,
  Barber = 71,
  LosSantosCustoms,
  Clothes,
  TattooParlor = 75,
  Simeon,
  Lester,
  Michael,
  Trevor,
  Heist1,
  Rampage = 84,
  VinewoodTours,
  Franklin,
  Franklin2 = 88,
  Chinese,
  FlightSchool,
  Bar = 93,
  ParachuteJump,
  Heist2 = 96,
  CarWash = 100,
  ComedyClub = 102,
  Darts,
  FIB = 106,
  Heist3,
  DollarSign,
  Golf,
  AmmuNation,
  Exile = 112,
  ShootingRange = 119,
  Solomon,
  StripClub,
  Tennis,
  Triathlon = 126,
  OffRoadRaceFinish,
  Key = 134,
  MovieTheater,
  Music,
  Marijuana = 140,
  Hunting,
  ArmsTraffickingGround = 147,
  Nigel = 149,
  AssaultRifle,
  Bat,
  Grenade,
  Health,
  Knife,
  Molotov,
  Pistol,
  RPG,
  Shotgun,
  SMG,
  Sniper,
  SonicWave,
  PointOfInterest,
  GTAOPassive,
  GTAOUsingMenu,
  Link = 171,
  Minigun = 173,
  GrenadeLauncher,
  Armor,
  Castle,
  CameraIcon = 184,
  Handcuffs = 188,
  Yoga = 197,
  Cab,
  Number11,
  Number12,
  Number13,
  Number14,
  Number15,
  Number16,
  Shrink,
  Epsilon,
  PersonalVehicleCar = 225,
  PersonalVehicleBike,
  Custody = 237,
  ArmsTraffickingAir = 251,
  Fairground = 266,
  PropertyManagement,
  Altruist = 269,
  Enemy,
  Chop = 273,
  Dead,
  Hooker = 279,
  Friend,
  BountyHit = 303,
  GTAOMission,
  GTAOSurvival,
  CrateDrop,
  PlaneDrop,
  Sub,
  Race,
  Deathmatch,
  ArmWrestling,
  AmmuNationShootingRange = 313,
  RaceAir,
  RaceCar,
  RaceSea,
  GarbageTruck = 318,
  Motorcycle = 348,
  SafehouseForSale = 350,
  Package,
  MartinMadrazo,
  EnemyHelicopter,
  Boost,
  Devin,
  Marina,
  Garage2,
  GolfFlag,
  Hangar,
  Helipad,
  JerryCan,
  Masks,
  HeistSetup,
  Incapacitated,
  PickupSpawn,
  BoilerSuit,
  Completed,
  Rockets,
  GarageForSale,
  HelipadForSale,
  MarinaForSale,
  HangarForSale,
  Business = 374,
  BusinessForSale,
  RaceBike,
  Parachute,
  TeamDeathmatch,
  RaceFoot,
  VehicleDeathmatch,
  Barry,
  Dom,
  MaryAnn,
  Cletus,
  Josh,
  Minute,
  Omega,
  Tonya,
  Paparazzo,
  Crosshair,
  Creator = 398,
  CreatorDirection,
  Abigail,
  Blimp,
  Repair,
  Testosterone,
  Dinghy,
  Fanatic,
  GangAttack,
  Information,
  CaptureBriefcase,
  LastTeamStanding,
  Boat,
  CaptureHouse,
  JerryCan2 = 415,
  RPLogo,
  GTAOPlayerSafehouse,
  GTAOPlayerSafehouseBounty,
  CaptureAmericanFlag,
  CaptureFlag,
  Tank,
  PlayerHelicopter,
  PlayerPlane,
  PlayerJet,
  PlayerArrowNoColor,
  PlayerLAPV,
  PlayerBoat,
  HeistRoom,
  Stopwatch = 430,
  DollarSignCircled,
  Crosshair2,
  Crosshair3,
  DollarSignSquared,
  RaceFlagWithArrow,
  Fire,
  DoubleDeathmatchSkulls,
  CastleIcon,
  Crown,
  SupplyBag,
  QuadirectionalArrows,
  Fox,
  Triangle,
  ThreeBars,
  LamarDavis,
  Mechanic,
  LamarDavisOne,
  LamarDavisTwo,
  LamarDavisThree,
  LamarDavisFour,
  LamarDavisFive,
  LamarDavisSix,
  LamarDavisSeven,
  LamarDavisEight,
  Yacht,
  SmallQuestionMark,
  GymBag,
  CrosshairWithPersonInMiddle,
  PlayerSpeaking,
  Taxi,
  ShieldWithX,
  YachtMinimap,
  Fox2,
  Hourglass,
  SmallQuestionMark2,
  Stopwatch2,
  Restart,
  SunWithEye,
  Marijuana2,
  Shotgun2,
  Jetski,
  EyeWithLineThroughIt,
  Garage3,
  GarageForSale2,
  Building,
  BuildingForSale,
  Truck,
  Crate,
  Trailer,
  Person,
  Cargobob,
  BigOutlineSquare,
  Speedometer,
  Ghost,
  RemoteControl,
  Bomb,
  Shield,
  StuntRace,
  Heart,
  StuntRaceMoney,
  TeamDeathMatch2,
  HouseWithGarage,
  QuadirectionalArrowsWithMotorcycle,
  CircleWithMotorcycle,
  MotorcycleRace,
  Weed,
  Cocaine,
  ForgedDocuments,
  Meth,
  CounterfeitMoney,
  DrugPickup,
  BigOne,
  BigTwo,
  BigThree,
  BigFour,
  BigFive,
  BigSix,
  BigSeven,
  BigEight,
  BigNine,
  BigTen,
  ATVQuad,
  Bus,
  BagMaybe,
  UpArrowOnSquare,
  FourPlayers,
  EightPlayers,
  TenPlayers,
  TwelvePlayers,
  SixteenPlayers,
  Laptop,
  Supercycle,
  Supercar,
  GarageWithCar,
  PaperDocument,
  ShieldWithBlackStar,
  CraneClaw,
  PhantomWedge,
  BoxvilleArmored,
  Ruiner2000,
  RampBuggy,
  Wastelander,
  RocketVoltic,
  TechnicalAqua,
  LetterA,
  LetterB,
  LetterC,
  LetterD,
  LetterE,
  LetterF,
  LetterG,
  LetterH,
  SkullWithTriangleTop,
  Wrench,
  SteeringWheel,
  Trolphy,
  Rocket,
  Missile,
  Bullets,
  Parachute2,
  Number5WithCircle,
  Number10WithCircle,
  Number15WithCircle,
  Number20WithCircle,
  Number30WithCircle,
  Bullets2,
  Bunker,
  InsurgentPickup,
  Opressor,
  TechnicalCustom,
  DuneFAV,
  HalfTrack,
  AntiAircraftTrailer,
  Satelite,
  BunkerWithPeople,
  ScrewdriverAndHammer,
  UpgradedWeaponWorkbench,
  CrateWithStraps,
  AircraftHanger,
  Icosikaitetragon,
  RaceflagWithQuestionmark,
  AlphaZ1,
  Bombushka,
  Havok,
  HowardNX25,
  Hunter,
  Ultralight,
  Mogul,
  Molotok,
  Nokota,
  Pyro,
  Rogue,
  Starling,
  Starbreeze,
  Tula,
  GymBagWithLetterH,
  LockedCrate,
  SateliteIcon,
  Avenger,
  IAAFacility,
  DoomsdayHeist,
  SAMTurret,
  HackingPuzzleRed,
  HackingPuzzleDiode,
  Stromburg,
  Deluxo,
  ThrusterJetpack,
  TM02KhanjaliTank,
  RCV,
  Volatol,
  Barrage,
  Akula,
  Chernobog,
  SpeakerMaybe,
  YellowishBrownMoneySign,
  ComputerTerminal,
  HackingPuzzleMirror,
  HackingPuzzleReflector,
  HackingPuzzleRotator,
  RaceFlagWithCrosshair,
  RaceFlagWithSteeringWheel,
  SeaSparrow,
  Caracara,
  Nightclub,
  CrateB,
  VanB,
  Diamond,
  BullionStacks,
  CalculatorMaybe,
  CarWithLightningBolt,
  HeartIcon,
  StarWithAdd,
  StarWithSubtract,
  BombWithAdd,
  BombWithSubtract,
  CrosshairDJ,
  Drone,
  Cashregister,
  SpeakerMaybeBigger,
  Skull,
  FestivalBus,
  Terrorbyte,
  Menacer,
  Scramjet,
  PounderCustom,
  MuleCustom,
  SpeedoCustom,
  BlimpIcon,
  OpressorMKII,
  B11StrikeForce,
  GearWithCar,
  GearWithMoney,
  GearWithWrench,
  RaceFlagWithGear,
  CrosshairOnCar,
  RCBandito,
  RCRemote,
  FlameSign,
  ArrowSign,
  GearSign,
  RepeatSign,
  DownArrowSign,
  ExplosionSign,
  WheelExplosionSign,
  ElevatorSign,
  ElevatorSign2,
  EjectorPlatformSign,
  Bruiser,
  Brutus,
  Cerberus,
  Deathbike,
  Dominator,
  Impaler,
  Imperator,
  Issi,
  Sasquatch,
  Scarab,
  Slamvan,
  ZR380
};

enum class BlipColors {
  None,
  Red,
  Green,
  Blue,
  PlayerColor,
  YellowMission,
  FriendlyVehicle = 0x26,
  MichaelColor = 0x2A,
  FranklinColor,
  TravorColor,
  BlipColorEnemy = 0x31,
  MissionVehicle = 0x36,
  RedMission = 0x3B,
  YellowMission2 = 0x3C,
  Mission = 0x42,
  WaypointColor = 0x54
};

enum class BlipDisplayBits {
  BlipIsBright = (1 << 1),
  BlipEngageFlashing = (1 << 3),
  BlipFlashForRoute = (1 << 5),
  BlipIsOnMinimap = (1 << 6),
  BlipIsHighDetail = (1 << 8),
  BlipUseBlipColorForDirection = (1 << 9),
  BlipIsSmall = (1 << 10),
  BlipShowCone = (1 << 11),
  BlipIsMissionCreatorBlip = (1 << 12),
  BlipShowCheckmark = (1 << 15),
  BlipShowDollarSign = (1 << 16),
  BlipShowHeadingIndicator = (1 << 17),
  BlipShowFullCircle = (1 << 18),
  BlipIsFriend = (1 << 19),
  BlipIsCrew = (1 << 20),
  BlipIsSelected = (1 << 22),
};

enum class BlipRenderBits {
  BlipIsOnScreen = (1 << 6)
};
// blip enums end

// explosion enums start
enum eExplosionType {
  DONTCARE = -1,
  GRENADE,
  GRENADELAUNCHER,
  STICKYBOMB,
  MOLOTOV,
  ROCKET,
  TANKSHELL,
  HI_OCTANE,
  CAR,
  PLANE,
  PETROL_PUMP,
  BIKE,
  DIR_STEAM,
  DIR_FLAME,
  DIR_WATER_HYDRANT,
  DIR_GAS_CANISTER,
  BOAT,
  SHIP_DESTROY,
  TRUCK,
  BULLET,
  SMOKEGRENADELAUNCHER,
  SMOKEGRENADE,
  BZGAS,
  FLARE,
  GAS_CANISTER,
  EXTINGUISHER,
  PROGRAMMABLEAR,
  TRAIN,
  BARREL,
  PROPANE,
  BLIMP,
  DIR_FLAME_EXPLODE,
  TANKER,
  PLANE_ROCKET,
  VEHICLE_BULLET,
  GAS_TANK,
  BIRD_CRAP,
  RAILGUN,
  BLIMP2,
  FIREWORK,
  SNOWBALL,
  PROXMINE,
  VALKYRIE_CANNON,
  AIR_DEFENCE,
  PIPEBOMB,
  VEHICLEMINE,
  EXPLOSIVEAMMO,
  APCSHELL,
  BOMB_CLUSTER,
  BOMB_GAS,
  BOMB_INCENDIARY,
  BOMB_STANDARD,
  TORPEDO,
  TORPEDO_UNDERWATER,
  BOMBUSHKA_CANNON,
  BOMB_CLUSTER_SECONDARY,
  HUNTER_BARRAGE,
  HUNTER_CANNON,
  ROGUE_CANNON,
  MINE_UNDERWATER,
  ORBITAL_CANNON,
  BOMB_STANDARD_WIDE,
  EXPLOSIVEAMMO_SHOTGUN,
  OPPRESSOR2_CANNON,
  MORTAR_KINETIC,
  VEHICLEMINE_KINETIC,
  VEHICLEMINE_EMP,
  VEHICLEMINE_SPIKE,
  VEHICLEMINE_SLICK,
  VEHICLEMINE_TAR,
  SCRIPT_DRONE,
  RAYGUN,
  BURIEDMINE,
  SCRIPT_MISSILE,
  RCTANK_ROCKET,
  BOMB_WATER,
  BOMB_WATER_SECONDARY,
  _0xF728C4A9,
  _0xBAEC056F,
  FLASHGRENADE,
  STUNGRENADE,
  _0x763D3B3B,
  SCRIPT_MISSILE_LARGE,
  SUBMARINE_BIG,
  EMPLAUNCHER_EMP
};

// explosion enums end

// sessiontype enums start
enum class eSessionType {
  JOIN_PUBLIC = 0,
  NEW_PUBLIC = 1,
  CLOSED_CREW = 2,
  CREW = 2,
  CLOSED_FRIENDS = 6,
  FIND_FRIEND = 9,
  SOLO,
  INVITE_ONLY,
  JOIN_CREW,
  SC_TV,
  LEAVE_ONLINE = -1
};

// sessiontype enums end

// transitionstate enum start
enum class eTransitionState {
  TRANSITION_STATE_EMPTY,
  TRANSITION_STATE_SP_SWOOP_UP,
  TRANSITION_STATE_MP_SWOOP_UP,
  TRANSITION_STATE_CREATOR_SWOOP_UP,
  TRANSITION_STATE_PRE_HUD_CHECKS,
  TRANSITION_STATE_WAIT_HUD_EXIT,
  TRANSITION_STATE_WAIT_FOR_SUMMON,
  TRANSITION_STATE_SP_SWOOP_DOWN,
  TRANSITION_STATE_MP_SWOOP_DOWN,
  TRANSITION_STATE_CANCEL_JOINING,
  TRANSITION_STATE_RETRY_LOADING,
  TRANSITION_STATE_RETRY_LOADING_SLOT_1,
  TRANSITION_STATE_RETRY_LOADING_SLOT_2,
  TRANSITION_STATE_RETRY_LOADING_SLOT_3,
  TRANSITION_STATE_RETRY_LOADING_SLOT_4,
  TRANSITION_STATE_WAIT_ON_INVITE,
  TRANSITION_STATE_PREJOINING_FM_SESSION_CHECKS,
  TRANSITION_STATE_LOOK_FOR_FRESH_JOIN_FM,
  TRANSITION_STATE_LOOK_TO_JOIN_ANOTHER_SESSION_FM,
  TRANSITION_STATE_CONFIRM_FM_SESSION_JOINING,
  TRANSITION_STATE_WAIT_JOIN_FM_SESSION,
  TRANSITION_STATE_CREATION_ENTER_SESSION,
  TRANSITION_STATE_PRE_FM_LAUNCH_SCRIPT,
  TRANSITION_STATE_FM_TEAMFULL_CHECK,
  TRANSITION_STATE_START_FM_LAUNCH_SCRIPT,
  TRANSITION_STATE_FM_TRANSITION_CREATE_PLAYER,
  TRANSITION_STATE_IS_FM_AND_TRANSITION_READY,
  TRANSITION_STATE_FM_SWOOP_DOWN,
  TRANSITION_STATE_POST_BINK_VIDEO_WARP,
  TRANSITION_STATE_FM_FINAL_SETUP_PLAYER,
  TRANSITION_STATE_MOVE_FM_TO_RUNNING_STATE,
  TRANSITION_STATE_FM_HOW_TO_TERMINATE,
  TRANSITION_STATE_START_CREATOR_PRE_LAUNCH_SCRIPT_CHECK,
  TRANSITION_STATE_START_CREATOR_LAUNCH_SCRIPT,
  TRANSITION_STATE_CREATOR_TRANSITION_CREATE_PLAYER,
  TRANSITION_STATE_IS_CREATOR_AND_TRANSITION_READY,
  TRANSITION_STATE_CREATOR_SWOOP_DOWN,
  TRANSITION_STATE_CREATOR_FINAL_SETUP_PLAYER,
  TRANSITION_STATE_MOVE_CREATOR_TO_RUNNING_STATE,
  TRANSITION_STATE_PREJOINING_TESTBED_SESSION_CHECKS,
  TRANSITION_STATE_LOOK_FOR_FRESH_JOIN_TESTBED,
  TRANSITION_STATE_LOOK_FOR_FRESH_HOST_TESTBED,
  TRANSITION_STATE_LOOK_TO_JOIN_ANOTHER_SESSION_TESTBED,
  TRANSITION_STATE_LOOK_TO_HOST_SESSION_TESTBED,
  TRANSITION_STATE_CONFIRM_TESTBED_SESSION_JOINING,
  TRANSITION_STATE_WAIT_JOIN_TESTBED_SESSION,
  TRANSITION_STATE_START_TESTBED_LAUNCH_SCRIPT,
  TRANSITION_STATE_TESTBED_TRANSITION_CREATE_PLAYER,
  TRANSITION_STATE_IS_TESTBED_AND_TRANSITION_READY,
  TRANSITION_STATE_TESTBED_SWOOP_DOWN,
  TRANSITION_STATE_TESTBED_FINAL_SETUP_PLAYER,
  TRANSITION_STATE_MOVE_TESTBED_TO_RUNNING_STATE,
  TRANSITION_STATE_TESTBED_HOW_TO_TERMINATE,
  TRANSITION_STATE_QUIT_CURRENT_SESSION_PROMPT,
  TRANSITION_STATE_WAIT_FOR_TRANSITION_SESSION_TO_SETUP,
  TRANSITION_STATE_TERMINATE_SP,
  TRANSITION_STATE_WAIT_TERMINATE_SP,
  TRANSITION_STATE_KICK_TERMINATE_SESSION,
  TRANSITION_STATE_TERMINATE_SESSION,
  TRANSITION_STATE_WAIT_TERMINATE_SESSION,
  TRANSITION_STATE_TERMINATE_SESSION_AND_HOLD,
  TRANSITION_STATE_TERMINATE_SESSION_AND_MOVE_INTO_HOLDING_STATE,
  TRANSITION_STATE_TEAM_SWAPPING_CHECKS,
  TRANSITION_STATE_RETURN_TO_SINGLEPLAYER,
  TRANSITION_STATE_WAIT_FOR_SINGLEPLAYER_TO_START,
  TRANSITION_STATE_WAITING_FOR_EXTERNAL_TERMINATION_CALL,
  TRANSITION_STATE_TERMINATE_MAINTRANSITION,
  TRANSITION_STATE_WAIT_FOR_DIRTY_LOAD_CONFIRM,
  TRANSITION_STATE_DLC_INTRO_BINK
};
// transitionstate enums end
}

#endif //GTA_BASE_ENUMS_HPP
