//
// Created by xray on 06/09/2023.
//

#include "util.hpp"

#define EXCEPTION_CASE_NAME(code, name) \
    case code:              \
        return xorstr_(name);

#define EXCEPTION_CASE(code) EXCEPTION_CASE_NAME(code, #code)

namespace base::logging::exception {
  std::string ExceptionCodeToStr(std::uint32_t code) {
    switch (code) {
      EXCEPTION_CASE(EXCEPTION_ACCESS_VIOLATION)
      EXCEPTION_CASE(EXCEPTION_DATATYPE_MISALIGNMENT)
      EXCEPTION_CASE(EXCEPTION_BREAKPOINT)
      EXCEPTION_CASE(EXCEPTION_SINGLE_STEP)
      EXCEPTION_CASE(EXCEPTION_ARRAY_BOUNDS_EXCEEDED)
      EXCEPTION_CASE(EXCEPTION_FLT_DENORMAL_OPERAND)
      EXCEPTION_CASE(EXCEPTION_FLT_DIVIDE_BY_ZERO)
      EXCEPTION_CASE(EXCEPTION_FLT_INEXACT_RESULT)
      EXCEPTION_CASE(EXCEPTION_FLT_INVALID_OPERATION)
      EXCEPTION_CASE(EXCEPTION_FLT_OVERFLOW)
      EXCEPTION_CASE(EXCEPTION_FLT_STACK_CHECK)
      EXCEPTION_CASE(EXCEPTION_FLT_UNDERFLOW)
      EXCEPTION_CASE(EXCEPTION_INT_DIVIDE_BY_ZERO)
      EXCEPTION_CASE(EXCEPTION_INT_OVERFLOW)
      EXCEPTION_CASE(EXCEPTION_PRIV_INSTRUCTION)
      EXCEPTION_CASE(EXCEPTION_IN_PAGE_ERROR)
      EXCEPTION_CASE(EXCEPTION_ILLEGAL_INSTRUCTION)
      EXCEPTION_CASE(EXCEPTION_NONCONTINUABLE_EXCEPTION)
      EXCEPTION_CASE(EXCEPTION_STACK_OVERFLOW)
      EXCEPTION_CASE(EXCEPTION_INVALID_DISPOSITION)
      EXCEPTION_CASE(EXCEPTION_GUARD_PAGE)
      EXCEPTION_CASE(EXCEPTION_INVALID_HANDLE)
      EXCEPTION_CASE_NAME(3221225474, "STATUS_NOT_IMPLEMENTED")
      EXCEPTION_CASE_NAME(3765269347, "EXCEPTION_MSVC_CPP")
      default:
        return xorstr_("UNKNOWN");
    }
  }
}