include(../vendor/fmt.cmake)
include(../vendor/result.cmake)
include(../vendor/magic_enum.cmake)
include(../vendor/spdlog.cmake)
include(../vendor/xorstr.cmake)
include(../vendor/zydis.cmake)
include(../vendor/gtest.cmake)
include(../vendor/glaze.cmake)