set(PROJECT_NAME_COPY ${PROJECT_NAME})
set(PROJECT_NAME ${PROJECT_NAME}_core)

find_package(imgui CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME} PUBLIC imgui::imgui dxgi)

include(../vendor/battery_embed.cmake)
include(../vendor/discord-presence.cmake)
include(../vendor/fmt.cmake)
include(../vendor/glaze.cmake)
include(../vendor/enchantum.cmake)
include(../vendor/pattern16.cmake)
include(../vendor/zydis.cmake)
include(../vendor/polyhook.cmake)
include(../vendor/result.cmake)
include(../vendor/spdlog.cmake)
include(../vendor/unordered_dense.cmake)
include(../vendor/xorstr.cmake)
include(../vendor/ctninja.cmake)
include(../vendor/argparse.cmake)
include(../vendor/minicoropp.cmake)
include(../vendor/stb.cmake)

set(PROJECT_NAME ${PROJECT_NAME_COPY})