set(PROJECT_NAME_COPY ${PROJECT_NAME})
set(PROJECT_NAME ${PROJECT_NAME}_core)

include(../vendor/battery_embed.cmake)
include(../vendor/discord-rpc.cmake)
include(../vendor/fmt.cmake)
include(../vendor/glaze.cmake)
include(../vendor/imgui.cmake)
include(../vendor/magic_enum.cmake)
include(../vendor/pattern16.cmake)
include(../vendor/zydis.cmake)
include(../vendor/polyhook.cmake)
include(../vendor/result.cmake)
include(../vendor/spdlog.cmake)
include(../vendor/tweeny.cmake)
include(../vendor/unordered_dense.cmake)
include(../vendor/xorstr.cmake)
include(../vendor/ctninja.cmake)

set(PROJECT_NAME ${PROJECT_NAME_COPY})