name: "Build & Analyze"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '17 7 * * 0'

jobs:
  build:
    name: Build & Analyze
    runs-on: windows-2025
    permissions:
      security-events: write
      packages: read

    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory

    strategy:
      fail-fast: false
      matrix:
        include:
          - language: actions
            build-mode: none
          - language: c-cpp
            build-mode: manual

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history of current branch

      - name: Fetch SonarCloud comparison branch (${{ github.base_ref }})
        if: matrix.language == 'c-cpp'
        run: |
          if ("${{ github.event_name }}" -eq "pull_request") {
            $TARGET_BRANCH="${{ github.base_ref }}"
            Write-Host "PR detected. Fetching target branch: $TARGET_BRANCH"
            git fetch origin ${TARGET_BRANCH}:refs/remotes/origin/${TARGET_BRANCH}
          } else {
            Write-Host "Fetching master branch"
            git fetch origin master:refs/remotes/origin/master
          }

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - name: Install build-wrapper
        if: matrix.language == 'c-cpp'
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v5.1.0

      - name: Build with build-wrapper
        if: matrix.language == 'c-cpp'
        run: |
          New-Item -ItemType directory -Path build
          cmake -S . -B build
          build-wrapper-win-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build build/ --config Release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

      - name: Run SonarCloud scan
        if: matrix.language == 'c-cpp'
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.cfamily.build-wrapper-output=${{ env.BUILD_WRAPPER_OUT_DIR }}
            -Dsonar.scm.provider=git